[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.term]
animation = "fromBottom"
command = "kitty --class kitty-float"
class = "kitty-float"
size = "75% 60%"
max_size = "1920px 100%"
unfocus = "hide"
lazy = true

[scratchpads.calc]
animation = "fromRight"
command = "gnome-calculator"
class = "org.gnome.Calculator"
size = "400px 60%"
max_size = "50% 100%"
unfocus = "hide"
lazy = true
close_on_hide = true
