#!/bin/zsh
#
eval "$(starship init zsh)"

# Create an amazing Zsh config using antidote plugins.
source /usr/share/zsh-antidote/antidote.zsh
antidote load

# Source anything in .zshrc.d.
for _rc in ${ZDOTDIR:-$HOME}/.zshrc.d/*.zsh; do
  # Ignore tilde files.
  if [[ $_rc:t != '~'* ]]; then
    source "$_rc"
  fi
done
unset _rc

# To customize prompt, run `p10k configure` or edit .p10k.zsh.
[[ ! -f ${ZDOTDIR:-$HOME}/.p10k.zsh ]] || source ${ZDOTDIR:-$HOME}/.p10k.zsh

# zoxide for a better cd
eval "$(zoxide init zsh)"

# history
HISTFILE=~/.zsh_history
HISTSIZE=2000
SAVEHIST=2000

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export JAVA_HOME=/opt/android-studio/jbr
export ANDROID_HOME="$HOME/Android/Sdk"
# export NDK_HOME="$ANDROID_HOME/ndk/$(ls -1 $ANDROID_HOME/ndk)"
export NDK_HOME="$ANDROID_HOME/ndk/29.0.13113456"

export COMPUTER_NAME="$(uname -n)"

export NODE_OPTIONS="--max-old-space-size=8192"

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath

alias unsetAWS='unset $(env | grep AWS | grep -v AWS_REGION | grep -v AWS_DEFAULT_REGION | sed '\''s|=.*||'\'')'

function assumeFunction {
   source assume $@
   # Serverless (SLS) fails when AWS_PROFILE is set, so we unset it here
   unset AWS_PROFILE
}

alias assume=assumeFunction

eval "$(atuin init zsh)"

enter() {
    if [[ -z $BUFFER ]]; then
        clear
        zle reset-prompt
    else
        zle accept-line
    fi
}

zle -N enter
bindkey "^M" enter
